// feat/project-scaffold — M1: Christian Adlawan
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans:     ['Outfit', 'sans-serif'],
        display:  ['Outfit', 'sans-serif'],
        mono:     ['JetBrains Mono', 'monospace'],
      },
      colors: {
        // ── Core brand (project) ──────────────────────────
        brand: {
          50:  '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        // ── Material Design tokens (auth pages + UI) ──────
        'primary':                    '#004ac6',
        'primary-container':          '#2563eb',
        'on-primary':                 '#ffffff',
        'primary-fixed':              '#dbe1ff',
        'primary-fixed-dim':          '#b4c5ff',
        'on-primary-fixed':           '#00174b',
        'on-primary-fixed-variant':   '#003ea8',
        'secondary':                  '#505f76',
        'secondary-container':        '#d0e1fb',
        'on-secondary':               '#ffffff',
        'secondary-fixed':            '#d3e4fe',
        'secondary-fixed-dim':        '#b7c8e1',
        'on-secondary-fixed':         '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'on-secondary-container':     '#54647a',
        'tertiary':                   '#943700',
        'tertiary-container':         '#bc4800',
        'on-tertiary':                '#ffffff',
        'tertiary-fixed':             '#ffdbcd',
        'tertiary-fixed-dim':         '#ffb596',
        'on-tertiary-fixed':          '#360f00',
        'on-tertiary-fixed-variant':  '#7d2d00',
        'on-tertiary-container':      '#ffede6',
        'surface':                    '#faf8ff',
        'surface-dim':                '#d2d9f4',
        'surface-bright':             '#faf8ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f2f3ff',
        'surface-container':          '#eaedff',
        'surface-container-high':     '#e2e7ff',
        'surface-container-highest':  '#dae2fd',
        'surface-variant':            '#dae2fd',
        'surface-tint':               '#0053db',
        'on-surface':                 '#131b2e',
        'on-surface-variant':         '#434655',
        'inverse-surface':            '#283044',
        'inverse-on-surface':         '#eef0ff',
        'inverse-primary':            '#b4c5ff',
        'background':                 '#faf8ff',
        'on-background':              '#131b2e',
        'outline':                    '#737686',
        'outline-variant':            '#c3c6d7',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:   '0.25rem',
        md:   '0.375rem',
        lg:   '0.5rem',
        xl:   '0.75rem',
        '2xl':'1rem',
        '3xl':'1.5rem',
        full: '9999px',
      },
      animation: {
        'fade-in':    'fadeIn 0.25s ease-out both',
        'slide-up':   'slideUp 0.3s ease-out both',
        'slide-in':   'slideIn 0.25s ease-out',
        'pulse-slow': 'pulse 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float':      'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:  { from: { opacity: 0 },                              to: { opacity: 1 } },
        slideUp: { from: { opacity: 0, transform: 'translateY(12px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideIn: { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        float:   {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-8px)' },
        },
      },
      transitionDelay: {
        75:  '75ms',
        150: '150ms',
        225: '225ms',
        300: '300ms',
      },
    },
  },
  plugins: [],
};